"""Regression goldens produced independently by GDAL 3.12.4."""

import json
from pathlib import Path

import numpy as np
import pytest
import tifffile
from pyproj import CRS

from app.services.raster.affine import Affine
from app.services.raster.fillnodata import fill_nodata_array, fill_nodata_geotiff
from app.services.raster.geotiff import GeoTiffReader, write_geotiff_array
from app.services.raster.overviews import add_overviews
from app.services.raster.reproject import plan_destination_grid

GOLD = json.loads((Path(__file__).parent / "fixtures/preprocess_gdal_3124.json").read_text())


@pytest.mark.parametrize("case", GOLD["fill"], ids=lambda c: c["name"])
@pytest.mark.parametrize("nan", [False, True])
def test_fill_matches_gdal(case, nan):
    data = np.array(case["input"], dtype="float32")
    expected = np.array(case["expected"], dtype="float32")
    if nan:
        data[data == -32768] = np.nan
        expected[expected == -32768] = np.nan
    actual = fill_nodata_array(data, nodata=np.nan if nan else -32768, max_distance=10)
    np.testing.assert_allclose(actual, expected, rtol=0, atol=1e-3, equal_nan=True)


def test_same_crs_grid_is_exact(tmp_path):
    p = tmp_path / "input.tif"
    a = Affine.north_up(130.0000000002, -5.0000000197, 0.0008333333300000009, 0.0008333333300000009)
    write_geotiff_array(p, np.zeros((513, 515), dtype="float32"), affine=a, crs=CRS.from_epsg(4326))
    with GeoTiffReader(p) as src:
        out, w, h = plan_destination_grid(src, src.crs)
        assert (w, h) == (src.width, src.height)
        assert out == src.affine


def test_reproject_grid_matches_gdal_3124_crop(tmp_path):
    # Golden generated by gdal raster reproject --dst-crs EPSG:3857.
    p = tmp_path / "crop.tif"
    affine = Affine.north_up(
        131.4999999942, -6.5000000137, 0.0008333333300000009, 0.0008333333300000009
    )
    write_geotiff_array(
        p, np.zeros((513, 515), dtype="float32"), affine=affine, crs=CRS.from_epsg(4326)
    )
    with GeoTiffReader(p) as src:
        a, w, h = plan_destination_grid(src, CRS.from_epsg(3857))
    assert (w, h) == (513, 515)
    np.testing.assert_allclose(
        a.to_gdal(),
        [14638513.03866982, 93.08592077439275, 0, -725133.786664975, 0, -93.08592077439275],
        rtol=0,
        atol=1e-7,
    )


@pytest.mark.parametrize("case", GOLD["grid"])
def test_projected_and_rotated_grid_golden(tmp_path, case):
    p = tmp_path / "grid.tif"
    write_geotiff_array(
        p,
        np.zeros((case["height"], case["width"]), dtype="float32"),
        affine=Affine.from_gdal(case["transform"]),
        crs=CRS.from_epsg(case["source"]),
    )
    with GeoTiffReader(p) as src:
        affine, width, height = plan_destination_grid(src, CRS.from_epsg(case["target"]))
    assert [width, height] == case["expected_size"]
    np.testing.assert_allclose(affine.to_gdal(), case["expected_transform"], rtol=0, atol=1e-7)


def test_odd_overview_matches_gdal(tmp_path):
    p = tmp_path / "input.tif"
    data = np.array(GOLD["overview"]["input"], dtype="float32")
    affine = Affine.north_up(130, -5, 0.001, 0.001)
    write_geotiff_array(
        p, data, affine=affine, crs=CRS.from_epsg(4326), nodata=-32768, block_size=16
    )
    add_overviews(p, block_size=16, workers=1)
    with tifffile.TiffFile(str(p) + ".ovr") as t:
        for page, expected in zip(t.pages, GOLD["overview"]["expected"], strict=True):
            np.testing.assert_allclose(page.asarray(), expected, rtol=0, atol=1e-3)
    with GeoTiffReader(p, preload=True) as src:
        assert src.overview_scales == [2, 4, 6, 10]
        level = src.select_level(src.width, src.height, 10, 9)
        assert (level.width, level.height) == (10, 9)
        np.testing.assert_allclose(
            src.read_window(0, 0, 9, 10, level=level)[:, :, 0],
            GOLD["overview"]["expected"][0],
            rtol=0,
            atol=1e-3,
        )


@pytest.mark.parametrize("budget", [4096, 1048576])
def test_fill_block_boundary_invariant(tmp_path, budget):
    a = np.array(GOLD["fill"][0]["input"], dtype="float32")
    p = tmp_path / "input.tif"
    out = tmp_path / "filled.tif"
    write_geotiff_array(
        p,
        a,
        affine=Affine.north_up(130, -5, 0.001, 0.001),
        crs=CRS.from_epsg(4326),
        nodata=-32768,
        block_size=16,
    )
    fill_nodata_geotiff(p, out, block_size=16, cache_bytes=budget)
    np.testing.assert_allclose(tifffile.imread(out), GOLD["fill"][0]["expected"], rtol=0, atol=1e-3)


def test_overview_unmasked_fractional_two_row_gdal_path(tmp_path):
    # GDAL's no-mask 2x2 optimization applies to the fractional tail row too.
    p = tmp_path / "input.tif"
    data = np.array([[0, 0, 10, 10], [20, 20, 30, 30], [100, 100, 110, 110]], dtype="float32")
    write_geotiff_array(
        p, data, affine=Affine.north_up(0, 3, 1, 1), crs=CRS.from_epsg(4326), block_size=16
    )
    add_overviews(p, levels=(2,), block_size=16)
    np.testing.assert_allclose(
        tifffile.imread(str(p) + ".ovr"), [[10, 20], [60, 70]], rtol=0, atol=1e-6
    )


def test_worker_cpu_and_memory_limits(monkeypatch):
    from app.services.raster import parallel

    monkeypatch.setattr(parallel.os, "cpu_count", lambda: 28)
    monkeypatch.setattr(parallel, "_cpu_quota_count", lambda: 4)
    monkeypatch.delenv("OTH_RASTER_WORKERS", raising=False)
    assert 1 <= parallel.default_workers() <= 4
    monkeypatch.setenv("OTH_RASTER_WORKERS", "2")
    assert 1 <= parallel.default_workers() <= 2
    assert parallel.raster_workers(1024, 512, 8) == 1
    monkeypatch.setenv("OTH_RASTER_WORKERS", "0")
    with pytest.raises(ValueError, match="positive integer"):
        parallel.default_workers()


def test_integer_cast_half_away_from_zero():
    from app.services.raster.resample import cast_sampled

    a = np.array([-2.5, -1.5, -0.5, 0.5, 1.5, 2.5], dtype="float32")
    np.testing.assert_array_equal(
        cast_sampled(a, np.dtype("int16"), nodata=None), [-3, -2, -1, 1, 2, 3]
    )


def test_no_holes_skips_fill_preserves_source_and_progress(tmp_path, monkeypatch):
    from app.schemas import PreprocessOptions
    from app.services import preprocessor

    p = tmp_path / "input.tif"
    a = np.arange(17 * 19, dtype="float32").reshape(17, 19)
    write_geotiff_array(
        p, a, affine=Affine.north_up(130, -5, 0.001, 0.001), crs=CRS.from_epsg(4326), block_size=16
    )
    original = p.read_bytes()

    def unexpected(*args, **kwargs):
        raise AssertionError("fill must be skipped after valid-pixel scan")

    monkeypatch.setattr(preprocessor, "fill_nodata_geotiff", unexpected)
    events = []
    out = preprocessor.preprocess_dem(
        p,
        tmp_path / "work",
        PreprocessOptions(block_size=16),
        64,
        on_subprogress=lambda pct, msg: events.append((pct, msg)),
    )
    np.testing.assert_array_equal(tifffile.imread(out), a)
    assert p.read_bytes() == original
    assert [e[0] for e in events] == sorted(e[0] for e in events)
    assert any("skipped" in (msg or "") for _, msg in events)
    assert not (out.parent / "filled.tif").exists()
    assert Path(str(out) + ".ovr").exists()
    # A reused work directory with overviews disabled must not retain old ones.
    preprocessor.preprocess_dem(
        p, tmp_path / "work", PreprocessOptions(block_size=16, build_overviews=False), 64
    )
    assert not Path(str(out) + ".ovr").exists()
